version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: postgres-db
      DB_USER: admin
      DB_PASSWORD: 123456789
      DB_PORT: 5432
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8000


  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: postgres-db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
